import { StyleSheet, Platform } from 'react-native';
import { Typography, Colors } from '../../styles';

const styles = StyleSheet.create({
  safeArea: {
    marginTop: Platform.OS === 'android' ? 25 : 40,
  },
  container: {
    flex: 1,
    backgroundColor: Colors.WHITE,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    height: 50,
    marginLeft: 10,
  },
  headerBefore: {
    color: Colors.PRIMARY,
  },
  headerTitle: {
    fontFamily: Typography.FONT_FAMILY_REGULAR,
    fontSize: Typography.FONT_SIZE_18,
    color: Colors.PRIMARY,
  },
  titleContent: {
    marginRight: 20,
  },
  BoxShoper: {
    marginTop: 10,
    marginHorizontal: 15,
    borderRadius: 50,
    padding: 5,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  BoxShoperContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  BoxShoperContentText: {
    marginLeft: 20,
    flexShrink: 1,
  },
  BoxShoperTitleTag: {
    color: Colors.WHITE,
    maxWidth: 175,
  },
  BoxShoperTitle: {
    fontFamily: Typography.FONT_FAMILY_BOLD,
    fontSize: Typography.FONT_SIZE_20,
  },
  boxImg: {
    width: 70,
    height: 70,
    borderRadius: 40,
    backgroundColor: Colors.WHITE,
    overflow: 'hidden',
  },
  BoxShoperImg: {
    width: 70,
    height: 70,
  },
  ButtonChat: {
    marginRight: 20,
  },
  timeline: {
    backgroundColor: Colors.WHITE,
    elevation: 5,
    marginVertical: 20,
    paddingVertical: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignContent: 'center',
  },
  risk: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: '50%',
  },
  riskLine: {
    width: '65%',
    height: 2,
    backgroundColor: Colors.GRAY_DARK,
    alignSelf: 'center',
  },
  boxStatus: {
    alignItems: 'center',
    flexGrow: 1,
  },
  boxStatusStep: {
    paddingTop: 4,
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  boxStatusStepBase: {
    textAlign: 'center',
    backgroundColor: Colors.WHITE,
    fontFamily: Typography.FONT_FAMILY_BOLD,
    fontSize: Typography.FONT_SIZE_20,
    width: 32,
    height: 32,
    lineHeight: 32,
    borderRadius: 15,
    overflow: 'hidden',
  },
  boxStatusStepText: {
    color: Colors.PRIMARY,
  },
  boxStatusStepTextD: {
    color: Colors.GRAY_DARK,
  },
  boxStatusText: {
    color: Colors.PRIMARY,
    fontSize: Typography.FONT_SIZE_15,
    fontFamily: Typography.FONT_FAMILY_BOLD,
  },
  boxStatusTextD: {
    color: Colors.GRAY_DARK,
    fontSize: Typography.FONT_SIZE_15,
    fontFamily: Typography.FONT_FAMILY_BOLD,
  },
  content: {
    // marginHorizontal: 15,
    flexGrow: 1,
    backgroundColor: Colors.WHITE,
    marginBottom: 50,
  },
  txtStatus: {
    fontFamily: Typography.FONT_FAMILY_BOLD,
    // lineHeight: 25,
    fontSize: Typography.FONT_SIZE_16,
    marginHorizontal: 15,
  },
  txtItens: {
    marginHorizontal: 15,
    fontFamily: Typography.FONT_FAMILY_REGULAR,
    fontSize: Typography.FONT_SIZE_16,
    lineHeight: 25,
    color: Colors.GRAY_DARK,
  },
  containerMap: {
    flexGrow: 1,
    marginTop: 20,
    justifyContent: 'flex-end',
    alignItems: 'flex-end',
    elevation: 1,
  },
  map: {
    ...StyleSheet.absoluteFillObject,
  },
  markerContainer: {},
  markerImage: {
    width: 30,
    height: 50,
  },
  iconDelivery: {
    color: Colors.PRIMARY,
  },
  txtTitleMap: {
    fontSize: Typography.FONT_SIZE_14,
    color: Colors.PRIMARY,
    fontFamily: Typography.FONT_FAMILY_BOLD,
  },
  boxOrder: {
    backgroundColor: Colors.WHITE,
    marginHorizontal: 15,
    marginBottom: 40,
    borderRadius: 10,
    elevation: 5,
    borderWidth: 1,
    borderColor: '#f9f9f9',
    paddingVertical: 5,
    paddingLeft: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  boxOrderContent: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  boxOrderContentText: {
    color: Colors.GRAY_DARK,
    fontSize: Typography.FONT_SIZE_18,
    marginLeft: 10,
  },
  boxItens: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: Colors.GRAY_LIGHT,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    marginTop: -10,
    paddingHorizontal: 25,
    elevation: 10,
    borderTopWidth: 1,
    borderLeftWidth: 1,
    borderRightWidth: 1,
    borderColor: Colors.GRAY_MEDIUM,
  },
  itensText: {
    fontSize: Typography.FONT_SIZE_15,
    fontFamily: Typography.FONT_FAMILY_BOLD,
    color: Colors.GRAY_DARK,
  },
  btnItens: {
    flexDirection: 'row',
    paddingHorizontal: '5%',
    paddingBottom: 5,
    backgroundColor: Colors.WHITE,
  },
  btnTxtItens: {
    fontSize: Typography.FONT_SIZE_15,
    color: Colors.WHITE,
    textAlign: 'center',
    alignItems: 'center',
    justifyContent: 'center',
  },
  BoxItemsOrder: {
    marginHorizontal: 15,
  },
  BoxItemsOrderContent: {
    backgroundColor: Colors.WHITE,
    borderRadius: 10,
    marginBottom: 10,
    elevation: 5,
    flexDirection: 'row',
    alignItems: 'center',
    overflow: 'hidden',
  },
  BoxItemsOrderImg: {
    width: 80,
    height: 80,
  },
  BoxItemsOrderText: {
    marginLeft: 15,
    marginRight: 15,
    fontSize: Typography.FONT_SIZE_14,
    color: Colors.GRAY_DARK,
    fontFamily: Typography.FONT_FAMILY_BOLD,
  },
  contentBadgeMessage: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    zIndex: 10,
  },
  badgeMessage: {
    backgroundColor: Colors.PRIMARY_DARK,
    borderRadius: 30,
    textAlign: 'center',
    color: Colors.WHITE,
    fontFamily: Typography.FONT_FAMILY_BOLD,
    width: 20,
    height: 20,
  },
  iconMessage: {
    marginTop: -10,
    zIndex: 5,
  },
  imageMessage: {
    width: 50,
    height: 50,
  },
  btnCart: {
    flex: 1,
    flexDirection: 'row',
    textAlign: 'center',
    borderRadius: 7,
    paddingHorizontal: 15,
    paddingVertical: 15,
    backgroundColor: 'transparent',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  imageBagCart: {
    width: 30,
    height: 30,
    alignItems: 'center',
    justifyContent: 'center',
  },
  itens: {
    color: Colors.WHITE,
    fontSize: Typography.FONT_SIZE_12,
    fontFamily: Typography.FONT_FAMILY_BOLD,
    marginRight: 3,
  },
  btnText: {
    fontSize: Typography.FONT_SIZE_15,
    fontFamily: Typography.FONT_FAMILY_MEDIUM,
    letterSpacing: 1,
    color: Colors.WHITE,
    textAlign: 'center',
  },
  pricePrimary: {
    fontSize: Typography.FONT_SIZE_14,
    color: Colors.WHITE,
    fontFamily: Typography.FONT_FAMILY_BOLD,
  },
  viewContentTitle: {
    backgroundColor: Colors.GREY_BACKGROUND,
    marginTop: 10,
    padding: 10,
    marginBottom: 5,
  },
  viewContentTitleTxt: {
    color: Colors.PRIMARY,
    fontSize: Typography.FONT_SIZE_16,
    fontFamily: Typography.FONT_FAMILY_MEDIUM,
  },
  viewContentInfo: {
    marginHorizontal: 15,
  },
  viewContentInfoTxt: {
    color: Colors.BLACK,
    fontSize: Typography.FONT_SIZE_14,
    fontFamily: Typography.FONT_FAMILY_REGULAR,
  },
  imageCard: {
    width: 30,
    height: 30,
    marginRight: 10,
  },
});

export default styles;
